feat!: add support for adding/setting user agent
waku-org/js-waku pull request #1016
Opened 2022-11-10 17:18 UTC by danisharora099

## Problem

This PR addresses https://github.com/waku-org/js-waku/issues/1009 focusing on adding the support for user agent on the libp2p instance.
The parent issue is: https://github.com/waku-org/pm/issues/3

## Solution

Added taking `userAgent` as an argument while creating any nodes, and setting whatever arbitrary value is passed by the user on the libp2p instance while creating the node -- the default value is set to `js-waku` but can be changed by the user if he requires.

2022-11-11 04:19 UTC, fryorcraken requested changes
How do we test this?

2022-11-11 04:19 UTC, fryorcraken commented on packages/core/src/lib/waku.ts
> +export const DefaultUserAgent = "waku-js";
```suggestion
export const DefaultUserAgent = "js-waku";
```

2022-11-11 04:19 UTC, fryorcraken commented on packages/create/src/index.ts
> +        host: userAgent || DefaultUserAgent,
```suggestion
        host: userAgent ?? DefaultUserAgent,
```

If you use `||` then empty string `0` and number value `0` will be overridden by the default user agent which is not the behaviour we'd expect AFAIK.

2022-11-14 01:05 UTC, fryorcraken commented on packages/create/src/index.ts
> +import { DefaultUserAgent } from "@waku/core/lib/waku";
```suggestion
import { DefaultUserAgent } from "@waku/core";
```
and in this case you need to re-export `DefaultUserAgent` in `core/src/index.ts`

OR

```suggestion
import { waku } from "@waku/core";
const { DefaultUserAgent } = waku;
```

2022-11-15 19:28 UTC, danisharora099 commented
Having set the agent version following https://github.com/libp2p/js-libp2p/pull/1296/files, but unable to retrieve the arbitrary agentVersion/host set using `const storedAgentVersion = await libp2p.peerStore.metadataBook.getValue(peerId, 'AgentVersion')` for some reason 

The expected value is `js-waku` but receiving the libp2p default  `js-libp2p/0.0.0 UserAgent=v16.13.1`
Added a test case to reproduce the use case

2022-11-16 00:06 UTC, fryorcraken commented on packages/tests/tests/waku.node.spec.ts
> +    await waku.dial(multiAddrWithId);
Why are you dialing the `nwaku` node? You don't seem to be using that.

2022-11-16 00:06 UTC, fryorcraken commented on packages/tests/tests/waku.node.spec.ts
> +      waku.libp2p.peerId
I am pretty sure the peer store only store info about other peers.
You are trying to get the info your your own node out of the peer store. I am surprised you are getting anything out of it.

A more appropriate test would be to connect 2 js-waku nodes together, set the user agent on one node and check from the **other node** whether it worked.

2022-11-16 20:15 UTC, danisharora099 commented
The tests keep failing locally for me: 
example test failing:
```       Bootstrap
         Passing an array:
     TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
      at new NodeError (node:internal/errors:371:5)
      at Function.from (node:buffer:322:9)
      at fromString (file:///Users/danisharora099/Developer/status/waku/node_modules/uint8arrays/esm/src/from-string.js:9:43)
      at IdentifyService.start (file:///Users/danisharora099/Developer/status/waku/node_modules/libp2p/src/identify/index.ts:128:109)
      at file:///Users/danisharora099/Developer/status/waku/node_modules/libp2p/src/libp2p.ts:305:46
      at Array.map (<anonymous>)
      at EventTarget.start (file:///Users/danisharora099/Developer/status/waku/node_modules/libp2p/src/libp2p.ts:305:23)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async WakuNode.start (file:///Users/danisharora099/Developer/status/waku/packages/core/src/lib/waku.ts:174:5)
      at async Context.<anonymous> (file:///Users/danisharora099/Developer/status/waku/packages/tests/tests/waku.node.spec.ts:77:7)```

2022-11-17 01:08 UTC, fryorcraken approved these changes

2022-11-17 07:26 UTC, merged