fix: Handle local storage missing when saving peers
waku-org/js-waku pull request #1954
Opened 2024-04-09 12:57 UTC by EmilIvanichkovv

## Problem
Trigger local storage missing error when calling `savePeersToLocalStorage` in `nodejs`

## Solution

Wrap the problematic block of code with a `try-catch` clause to handle any potential errors.

## Notes

- Resolves https://github.com/waku-org/js-waku/issues/1953

Contribution checklist:
- [ ] covered by unit tests;
- [ ] covered by e2e test;
- [ ] add `!` in title if breaks public API;

2024-04-11 07:58 UTC, adklempner requested changes
Please fix the prettier error and rebase

2024-04-11 07:58 UTC, adklempner commented on packages/discovery/src/local-peer-cache/index.ts
> +    try{
you need to insert a space here `try {`

2024-04-11 12:35 UTC, EmilIvanichkovv commented on packages/discovery/src/local-peer-cache/index.ts
> +    try{
Sorry for missing this

2024-04-11 14:50 UTC, weboko approved these changes

2024-04-12 15:03 UTC, weboko commented
Closing in favor of https://github.com/waku-org/js-waku/pull/1956

2024-04-12 15:03 UTC, closed without merging