chore: upgrade to 0.32
waku-org/js-waku pull request #2170
Opened 2024-10-09 07:02 UTC by danisharora099

## Problem

## Solution

 

## Notes

- Resolves <issue number>
- Related to <link to specs>

Contribution checklist:
- [ ] covered by unit tests;
- [ ] covered by e2e test;
- [ ] add `!` in title if breaks public API;

2025-01-23 00:51 UTC, weboko commented
Is it ready for review? Both test steps has failed :(

2025-01-23 08:55 UTC, danisharora099 commented
> Is it ready for review? Both test steps has failed :(

All of the tests seem to pass, but the CI runner doesn't seem to exit out of the process
Investigating

2025-02-04 20:57 UTC, adklempner approved these changes

2025-02-04 21:20 UTC, weboko commented on packages/tests/.mocharc.cjs
> +  timeout: 150_000
why 2 retries and 150_000 timeout?

2025-02-04 21:26 UTC, weboko commented on packages/tests/src/lib/index.ts
> +      while (Date.now() - startTime < maxTimeout) {
is loop needed here? we can hit endless cycle

2025-02-04 21:28 UTC, weboko commented on packages/tests/tests/ephemeral.node.spec.ts
> +    await teardownNodesWithRedundancy(additionalServiceNodes, [waku1, waku2]);
it seems wrong: `additionalServiceNodes` is created just to be teared down at the next line

2025-02-04 21:29 UTC, weboko commented on packages/tests/tests/light-push/index.node.spec.ts
> +        if (pushResponse.failures.length > 0) console.log(i + 1);
should be removed

2025-02-04 21:29 UTC, weboko commented on packages/tests/tests/light-push/index.node.spec.ts
> +    it("Push 5 different messages", async function () {
the test is changed, why?

2025-02-04 21:29 UTC, weboko commented on packages/tests/tests/light-push/index.node.spec.ts
> +    it("Push 5 different messages", async function () {
in other places in the file too

2025-02-04 21:33 UTC, weboko commented on packages/tests/tests/store/multiple_pubsub.spec.ts
> -  it("Generator, 2 nwaku nodes each with different pubsubtopics", async function () {
why removed? it seems like a viable test case

2025-02-04 21:34 UTC, weboko requested changes
overall looks good, asked some questions and let's remove logs

2025-02-05 12:23 UTC, danisharora099 commented on packages/tests/src/lib/index.ts
> +      while (Date.now() - startTime < maxTimeout) {
valid concern; moved to promsies + timeout: e095c4799dc3391e9a9dd2deecc34f42e736a54c

2025-02-05 12:25 UTC, danisharora099 commented on packages/tests/tests/ephemeral.node.spec.ts
> +    await teardownNodesWithRedundancy(additionalServiceNodes, [waku1, waku2]);
fair - f5ac8c1390e01511ad978e14e614e17a73630c2d

2025-02-05 12:36 UTC, danisharora099 commented on packages/tests/tests/store/multiple_pubsub.spec.ts
> +      await serviceNodes.sendRelayMessage(
true, something buggy with the autosharding API, confirming -- similar reason for https://github.com/waku-org/js-waku/pull/2170#discussion_r1941925908

2025-02-10 21:06 UTC, weboko approved these changes

2025-02-10 21:07 UTC, weboko commented
looks good, node tests fail tho

2025-02-17 13:51 UTC, merged